name:                leitner
version:             0.1.0.0
synopsis:            Command line flashcard learning system based on the Leitner method
#description:
homepage:            https://github.com/noughtmare/leitner#readme
license:             GPL-3
author:              Jaro Reinders
maintainer:          noughtmare@openmailbox.com
copyright:           2017 Jaro Reinders
category:            Learning
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - optparse-applicative

executables:
  leitner:
    source-dirs:      src
    main:             Main.hs
